field: cf4aeda7-b961-4f8f-b730-997045ee9333 # Content Blocks
fieldLayouts:
  7b481c2a-ef9c-4869-904e-e2ddd2df3745:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5b01342c-dfe1-424a-a3eb-1208dd9e1501 # Markdown Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ca05756-7af9-4c96-aea2-bc9b35e73a83
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 03780ca7-7649-4589-b2a9-e2a71836628b
        userCondition: null
fields:
  5b01342c-dfe1-424a-a3eb-1208dd9e1501: # Markdown Text
    columnSuffix: kbhzvhzm
    contentColumnType: text
    fieldGroup: null
    handle: markdownText
    instructions: null
    name: 'Markdown Text'
    searchable: false
    settings:
      enableLineWrapping: true
      enableSpellChecker: false
      enabledToolbarIconNames:
        - bold
        - italic
        - quote
        - ordered-list
        - unordered-list
        - link
        - image
        - doxter-users
        - doxter-entries
        - doxter-assets
        - doxter-tags
      indentWithTabs: false
      showToolbar: true
      tabSize: 2
    translationKeyFormat: null
    translationMethod: none
    type: verbb\doxter\fields\Doxter
handle: markdownText
name: 'Markdown Text'
sortOrder: 1
