fieldLayouts:
  11d16970-489e-4cfb-a773-8bafd9ca67ae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a8efd0a5-79dd-408e-9c9b-5fd9cadd17c8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cf4aeda7-b961-4f8f-b730-997045ee9333 # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47532114-fd5b-411a-af6b-b6612eceb5a0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d15864c-97e7-4cb2-b002-c8efd3798ce3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 765671f0-816a-41a7-a815-195b50a11605
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 5a3c5172-d737-4cfd-88ef-0db2fb11f93e
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: bb209b2b-5ec6-466a-be46-0fed7805ba0c # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
