columnSuffix: nzchkrbt
contentColumnType: text
fieldGroup: ca240dbb-2270-468b-a5aa-d4dbc0fc7d91 # SEO
handle: siteName
instructions: null
name: 'Site Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
