currLabel: Plug-in-Store
customIcon: null
enabled: true
handle: plugin-store
icon: plugin
layout: bd7caa60-5db5-4a93-8daa-5fc181deaf28 # Default
level: 1
newWindow: false
parent: null
prevLabel: Plug-in-Store
prevLevel: 1
prevParent: null
prevUrl: plugin-store
sortOrder: 5
subnavBehaviour: null
type: craft
url: plugin-store
