currLabel: Einträge
customIcon: null
enabled: true
handle: entries
icon: section
layout: bd7caa60-5db5-4a93-8daa-5fc181deaf28 # Default
level: 1
newWindow: false
parent: null
prevLabel: Einträge
prevLevel: 1
prevParent: null
prevUrl: entries
sortOrder: 2
subnavBehaviour: null
type: craft
url: entries
