currLabel: Einstellungen
customIcon: null
enabled: true
handle: settings
icon: settings
layout: bd7caa60-5db5-4a93-8daa-5fc181deaf28 # Default
level: 1
newWindow: false
parent: null
prevLabel: Einstellungen
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 4
subnavBehaviour: null
type: craft
url: settings
