currLabel: Werkzeuge
customIcon: null
enabled: true
handle: utilities
icon: tool
layout: bd7caa60-5db5-4a93-8daa-5fc181deaf28 # Default
level: 1
newWindow: false
parent: null
prevLabel: Werkzeuge
prevLevel: 1
prevParent: null
prevUrl: utilities
sortOrder: 3
subnavBehaviour: null
type: craft
url: utilities
