defaultPlacement: end
enableVersioning: true
handle: globalSeo
name: SEO
propagationMethod: all
siteSettings:
  e6d6312f-5bfe-4933-80d2-be986487da24: # German
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: global-seo
type: single
